import Layout from '@/components/layout'
import Link from 'next/link'
import { getAllPosts } from '@/lib/api'



export default function Index({ allPosts = [] }) {
  return (
    <Layout>
      <h1>MDX Posts Page</h1>
      <p>
        Click the link below to navigate to a page generated by{' '}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {allPosts.map((post) => (
          <li key={post.filePath}>
            <Link
              as={`articles/${post.slug.replace(/\.mdx?$/, '')}`}
              href={`articles/[slug]`}
            >
              <a>{post.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </Layout>
  )
}

export async function getStaticProps() {
  const allPosts = getAllPosts([
    'title',
    'date',
    'slug',
    'author',
    'coverImage',
    'excerpt',
    'tags,'
  ])

  return {
    props: { allPosts },
  }
}
